# Generated by Django 6.0.3 on 2026-07-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0012_alter_action_action_alter_background_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text_preset_from_shots', 'Refine from shots'), ('generate_text_preset_from_prompt', 'Refine from prompt'), ('generate_text_preset_translate', 'Translate from prompt'), ('extract_scene', 'Sync structure')], null=True, verbose_name='action'),
        ),
    ]
