# Generated by Django 6.0.3 on 2026-07-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0013_alter_scene_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='name')),
                ('preset', models.JSONField(blank=True, null=True, verbose_name='preset')),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Elements'), ('generate_scene_actions', 'Generate Shots'), ('generate_scene_voices', 'Generate Voices'), ('generate_scene_comics', 'Generate Comics'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='background',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Elements'), ('generate_scene_actions', 'Generate Shots'), ('generate_scene_voices', 'Generate Voices'), ('generate_scene_comics', 'Generate Comics'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='character',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Elements'), ('generate_scene_actions', 'Generate Shots'), ('generate_scene_voices', 'Generate Voices'), ('generate_scene_comics', 'Generate Comics'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='prop',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Elements'), ('generate_scene_actions', 'Generate Shots'), ('generate_scene_voices', 'Generate Voices'), ('generate_scene_comics', 'Generate Comics'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='story',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Elements'), ('generate_scene_actions', 'Generate Shots'), ('generate_scene_voices', 'Generate Voices'), ('generate_scene_comics', 'Generate Comics'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='syncitem',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Elements'), ('generate_scene_actions', 'Generate Shots'), ('generate_scene_voices', 'Generate Voices'), ('generate_scene_comics', 'Generate Comics'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AddField(
            model_name='story',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='scene.preset', verbose_name='config'),
        ),
    ]
