# Generated by Django 5.2.15 on 2026-07-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scene", "0013_previous_image"),
        ("scene", "0013_render_document_config"),
    ]

    operations = []
