# Generated by Django 5.2.15 on 2026-07-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scene", "0013_scene_order_nullable"),
        ("scene", "0014_merge_0013_previous_image_0013_render_document_config"),
    ]

    operations = []
