# Generated by Django 6.0.3 on 2026-07-24 22:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_historicalprompt'),
        ('scene', '0014_preset_alter_action_action_alter_background_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='prompt_elements',
            field=models.TextField(blank=True, default='#Plot\n', null=True, verbose_name='prompt'),
        ),
        migrations.CreateModel(
            name='HistoricalScene',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('prompt', models.TextField(blank=True, default='#Shots\n', null=True, verbose_name='prompt')),
                ('prompt_refine', models.TextField(blank=True, null=True, verbose_name='prompt refine')),
                ('action', models.SlugField(blank=True, choices=[('generate_text_preset_from_shots', 'Refine from shots'), ('generate_text_preset_from_prompt', 'Refine from prompt'), ('generate_text_preset_translate', 'Translate from prompt'), ('extract_scene', 'Sync structure')], null=True, verbose_name='action')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.author', verbose_name='author')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.story', verbose_name='story')),
            ],
            options={
                'verbose_name': 'historical scene',
                'verbose_name_plural': 'historical scenes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('prompt', models.TextField(blank=True, default='#Plot\n', null=True, verbose_name='prompt')),
                ('prompt_refine', models.TextField(blank=True, null=True, verbose_name='prompt refine')),
                ('prompt_elements', models.TextField(blank=True, default='#Plot\n', null=True, verbose_name='prompt')),
                ('action', models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Elements'), ('generate_scene_actions', 'Generate Shots'), ('generate_scene_voices', 'Generate Voices'), ('generate_scene_comics', 'Generate Comics'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action')),
                ('render_type', models.CharField(choices=[('film', 'Film'), ('comic', 'Graphic Novel'), ('animatic', 'Animatic')], default='animatic', help_text='The default render format for this story.', max_length=50, verbose_name='render type')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('config', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.preset', verbose_name='config')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, help_text='Auto create authors from this group, it happens only when the script is saved for the first time', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.storygroup', verbose_name='group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agent.agent', verbose_name='mentor')),
                ('style', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.style', verbose_name='style')),
                ('theme', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.theme', verbose_name='theme')),
            ],
            options={
                'verbose_name': 'historical Story',
                'verbose_name_plural': 'historical Stories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
