# Generated by Django 6.0.3 on 2026-08-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0015_story_prompt_elements_historicalscene_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['order'], 'verbose_name': 'Shot', 'verbose_name_plural': 'Shots'},
        ),
        migrations.AddField(
            model_name='historicalscene',
            name='prompt_elements',
            field=models.TextField(blank=True, null=True, verbose_name='Prompt Elements'),
        ),
        migrations.AddField(
            model_name='historicalscene',
            name='prompt_plot',
            field=models.TextField(blank=True, null=True, verbose_name='Prompt Plot'),
        ),
        migrations.AddField(
            model_name='scene',
            name='prompt_elements',
            field=models.TextField(blank=True, null=True, verbose_name='Prompt Elements'),
        ),
        migrations.AddField(
            model_name='scene',
            name='prompt_plot',
            field=models.TextField(blank=True, null=True, verbose_name='Prompt Plot'),
        ),
        migrations.AlterField(
            model_name='historicalscene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text_preset_adapt', 'Adapt Prompt'), ('generate_text_preset_from_shots', 'Refine from shots'), ('generate_text_preset_from_prompt', 'Refine from prompt'), ('generate_text_preset_translate', 'Translate from prompt'), ('generate_text_preset_sync_elements', 'Sync structure'), ('extract_scene', 'Generate structure')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='historicalstory',
            name='prompt_elements',
            field=models.TextField(blank=True, default='#Locations\n#Characters\n#Props\n#Voices\n', null=True, verbose_name='Prompt Elements'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text_preset_adapt', 'Adapt Prompt'), ('generate_text_preset_from_shots', 'Refine from shots'), ('generate_text_preset_from_prompt', 'Refine from prompt'), ('generate_text_preset_translate', 'Translate from prompt'), ('generate_text_preset_sync_elements', 'Sync structure'), ('extract_scene', 'Generate structure')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='story',
            name='prompt_elements',
            field=models.TextField(blank=True, default='#Locations\n#Characters\n#Props\n#Voices\n', null=True, verbose_name='Prompt Elements'),
        ),
    ]
