# Generated by Django 6.0.3 on 2026-08-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0016_alter_action_options_historicalscene_prompt_elements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text_preset_adapt', 'Adapt Prompt'), ('generate_text_preset_from_shots', 'Refine from shots'), ('generate_text_preset_from_prompt', 'Refine from prompt'), ('generate_text_preset_translate', 'Translate from prompt'), ('generate_text_preset_sync_elements', 'Sync structure'), ('extract_scene', 'Generate structure'), ('generate_text_preset_info', 'Info'), ('generate_text_preset_instruction_schema_outwithmsg', 'Instruction')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text_preset_adapt', 'Adapt Prompt'), ('generate_text_preset_from_shots', 'Refine from shots'), ('generate_text_preset_from_prompt', 'Refine from prompt'), ('generate_text_preset_translate', 'Translate from prompt'), ('generate_text_preset_sync_elements', 'Sync structure'), ('extract_scene', 'Generate structure'), ('generate_text_preset_info', 'Info'), ('generate_text_preset_instruction_schema_outwithmsg', 'Instruction')], max_length=1024, null=True, verbose_name='action'),
        ),
    ]
