# Generated by Django 6.0.3 on 2026-08-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0017_alter_historicalscene_action_alter_scene_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscene',
            name='prompt_draft',
            field=models.TextField(blank=True, null=True, verbose_name='Prompt Draft from Plot'),
        ),
        migrations.AddField(
            model_name='scene',
            name='prompt_draft',
            field=models.TextField(blank=True, null=True, verbose_name='Prompt Draft from Plot'),
        ),
        migrations.AlterField(
            model_name='historicalscene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-scene_create_draft--target-prompt_draft', 'Draft from plot'), ('generate_text-preset-scene_edit_draft--target-prompt_draft', 'Edit draft'), ('generate_text-preset-scene_create_prompt', 'Create prompt from draft'), ('generate_text-preset-scene_edit_prompt', 'Edit from prompt'), ('generate_text-preset-scene_from_shots', 'Refine from shots'), ('generate_text-preset-translate', 'Translate from prompt'), ('generate_text-preset-scene_sync_elements', 'Sync structure'), ('extract_scene', 'Generate structure'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='historicalscene',
            name='prompt',
            field=models.TextField(blank=True, default='#Shots\n', null=True, verbose_name='Prompt Shots from Draft'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-scene_create_draft--target-prompt_draft', 'Draft from plot'), ('generate_text-preset-scene_edit_draft--target-prompt_draft', 'Edit draft'), ('generate_text-preset-scene_create_prompt', 'Create prompt from draft'), ('generate_text-preset-scene_edit_prompt', 'Edit from prompt'), ('generate_text-preset-scene_from_shots', 'Refine from shots'), ('generate_text-preset-translate', 'Translate from prompt'), ('generate_text-preset-scene_sync_elements', 'Sync structure'), ('extract_scene', 'Generate structure'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='prompt',
            field=models.TextField(blank=True, default='#Shots\n', null=True, verbose_name='Prompt Shots from Draft'),
        ),
    ]
