# Generated by Django 6.0.3 on 2026-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0020_historicalaction_historicalbackground_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='scene.character', verbose_name='cast'),
        ),
        migrations.AddField(
            model_name='scene',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='scene.background', verbose_name='locations'),
        ),
        migrations.AddField(
            model_name='scene',
            name='props',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='scene.prop', verbose_name='props'),
        ),
        migrations.AddField(
            model_name='scene',
            name='voices',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='scene.voice', verbose_name='voices'),
        ),
    ]
