# Generated by Django 6.0.3 on 2026-08-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0021_scene_cast_scene_locations_scene_props_scene_voices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-scene_create_draft-target-prompt_draft', 'Draft from plot'), ('generate_text-preset-scene_edit_draft-target-prompt_draft', 'Edit draft'), ('generate_text-preset-scene_create_prompt', 'Create prompt from draft'), ('generate_text-preset-scene_edit_prompt', 'Edit from prompt'), ('generate_text-preset-scene_from_shots', 'Refine from shots'), ('generate_text-preset-translate', 'Translate from prompt'), ('generate_text-preset-scene_sync_elements-schema-assets', 'Sync Elements'), ('extract_scene', 'Generate structure'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-scene_create_draft-target-prompt_draft', 'Draft from plot'), ('generate_text-preset-scene_edit_draft-target-prompt_draft', 'Edit draft'), ('generate_text-preset-scene_create_prompt', 'Create prompt from draft'), ('generate_text-preset-scene_edit_prompt', 'Edit from prompt'), ('generate_text-preset-scene_from_shots', 'Refine from shots'), ('generate_text-preset-translate', 'Translate from prompt'), ('generate_text-preset-scene_sync_elements-schema-assets', 'Sync Elements'), ('extract_scene', 'Generate structure'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
    ]
