# Generated by Django 6.0.3 on 2026-08-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0022_alter_historicalscene_action_alter_scene_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscene',
            name='prompt_draft',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='prompt_draft',
        ),
        migrations.AlterField(
            model_name='historicalscene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-scene_create_prompt', 'Create prompt from plot'), ('generate_text-preset-scene_edit_prompt', 'Edit prompt'), ('generate_text-preset-scene_from_shots', 'Edit shots'), ('generate_text-preset-translate', 'Translate shots'), ('generate_text-preset-scene_sync_elements-schema-assets', 'Sync Elements'), ('generate_text-preset-scene_sync_shots-schema-scene', 'Sync Shots'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-scene_create_prompt', 'Create prompt from plot'), ('generate_text-preset-scene_edit_prompt', 'Edit prompt'), ('generate_text-preset-scene_from_shots', 'Edit shots'), ('generate_text-preset-translate', 'Translate shots'), ('generate_text-preset-scene_sync_elements-schema-assets', 'Sync Elements'), ('generate_text-preset-scene_sync_shots-schema-scene', 'Sync Shots'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
    ]
