# Generated by Django 5.2.15 on 2026-08-19 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scene", "0023_remove_historicalscene_prompt_draft_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="What you call this batch, e.g. the date or 'batch AW'.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("author", "The author"),
                            ("agent", "An agent or tool"),
                            ("audit", "An audit or review"),
                        ],
                        default="author",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "received",
                    models.DateTimeField(auto_now_add=True, verbose_name="received"),
                ),
                (
                    "verbatim",
                    models.TextField(
                        help_text="Paste it exactly as received. Do not tidy it.",
                        verbose_name="verbatim",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_batches",
                        to="scene.story",
                        verbose_name="story",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback batch",
                "verbose_name_plural": "Feedback batches",
                "ordering": ["-received", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        help_text="Your own id for it, if you use one.",
                        max_length=50,
                        verbose_name="reference",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ask", "Ask"),
                            ("approval", "Approval"),
                            ("rule", "Standing rule"),
                            ("question", "Question"),
                        ],
                        default="ask",
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                (
                    "work",
                    models.CharField(
                        choices=[
                            ("text", "Words on the page"),
                            ("art", "The drawing"),
                            ("letter", "Lettering placement"),
                            ("order", "Reading order"),
                            ("add", "Add a panel"),
                            ("cut", "Cut a panel"),
                            ("move", "Move a panel"),
                            ("build", "Build or tooling"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="work",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("author", "The author"),
                            ("agent", "An agent or tool"),
                            ("audit", "An audit or review"),
                        ],
                        default="author",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "ask",
                    models.TextField(
                        help_text="Their words, not a summary of them.",
                        verbose_name="the ask",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("partial", "Partly done"),
                            ("done", "Done, not looked at"),
                            ("verified", "Verified on the page"),
                            ("moot", "Moot"),
                            ("superseded", "Superseded"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="What was done, and what is still not done.",
                        verbose_name="note",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="cost",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="scene.action",
                        verbose_name="panel",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="scene.scene",
                        verbose_name="scene",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="scene.story",
                        verbose_name="story",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="scene.feedback",
                        verbose_name="superseded by",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="scene.feedbackbatch",
                        verbose_name="batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
                "ordering": ["status", "-created", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="scene_feedb_status_b804b6_idx"
                    ),
                    models.Index(fields=["kind"], name="scene_feedb_kind_2812e1_idx"),
                ],
            },
        ),
    ]
