"""
Django settings for screenplay project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(dotenv_path=os.path.join(BASE_DIR, '.env'))
GOOGLE_GENAI_VERTEX_API_KEY= os.getenv("GOOGLE_GENAI_VERTEX_API_KEY")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
MEDIA_ROOT = os.path.join( BASE_DIR , 'media' )
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")


SITE_URL = os.getenv("SITE_URL")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['178.238.234.86', 'localhost', '127.0.0.1']
ALLOWED_HOSTS = ['178.238.234.86', 'guillermoai.duckdns.org', 'www.guillermoai.duckdns.org', 'guillermo.studio', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'easy_thumbnails',
    'filer',
    'scene.apps.SceneConfig',
    'agent.apps.AgentConfig',
    'task',
    'import_export',
    'unfold.contrib.import_export',
    'django_celery_beat',
    'crispy_forms',
    "unfold.contrib.simple_history",  # Makes the history UI match Unfold's Tailwind theme
    "simple_history",
    "unfold_markdown"
]


CRISPY_TEMPLATE_PACK = "unfold_crispy"
CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



# Brevo SMTP Server configuration
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = True


# Authentication credentials
# The login username is always the email address linked to your Brevo account
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# Your long Brevo SMTP key (looks like xsmtpsib-...)
EMAIL_HOST_PASSWORD = os.environ.get('SMTP_KEY', '')

# Default sender settings
# CRITICAL: This email address MUST be verified in your Brevo Sender dashboard
DEFAULT_FROM_EMAIL = 'Guillermo By Elio <noreply@guillermo.studio>'
SERVER_EMAIL = 'admin@guillermo.studio'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'
            ],
            'debug': DEBUG,
        },
    }
]

WSGI_APPLICATION = 'project.wsgi.application'


def agentprofile(request):
    try:
        return f"/admin/agent/agentprofile/{request.user.story_profile.id}/change/?next=/admin/scene/story/"
    except:
        return "/admin/"
def token_usage_link(request):
    return "/admin/agent/tokenusage/"

def storyprofile(request):
    try:
        return f"/admin/scene/storyprofile/{request.user.story_profile.id}/change/?next=/admin/scene/story/"
    except:
        return "/admin/scene/storyprofile/"


from django.templatetags.static import static

UNFOLD = {
    "SITE_TITLE": _("Guillermo"),  # Appears in the title and in the top left corner
    "SITE_HEADER": _("Guillermo"),
    "SITE_SUBHEADER": _("The power of your story"),
    "STYLES": [
        lambda request: static("css/unfold_filer_custom.css"),
        lambda request: static("css/custom.css"),
    ],
    "DASHBOARD_CALLBACK": "scene.models.dashboard_callback",
    "ACCOUNT": {}, # Empty this to prevent duplication at the bottom
    
    "COLORS": {
      "font": {
            "subtle-light": "var(--color-base-500)",  # text-base-500
            "subtle-dark": "var(--color-base-400)",  # text-base-400
            "default-light": "var(--color-base-600)",  # text-base-600
            "default-dark": "var(--color-base-300)",  # text-base-300
            "important-light": "var(--color-base-700)",  # text-base-900
            "important-dark": "var(--color-base-300)",  # text-base-100
        },
        "base": {
            "50": "oklch(98.5% .002 247.839)",
            "100": "oklch(96.7% .003 264.542)",
            "200": "oklch(92.8% .006 264.531)",
            "300": "oklch(87.2% .01 258.338)",
            "400": "oklch(70.7% .022 261.325)",
            "500": "oklch(55.1% .027 264.364)",
            "600": "oklch(44.6% .03 256.802)",
            "700": "oklch(37.3% .034 259.733)",
            "800": "oklch(27.8% .033 256.848)",
            "900": "oklch(21% .034 264.665)",
            "950": "oklch(13% .028 261.692)",
        },
        "primary": {
            "50": "oklch(97.7% .014 308.299)",
            "100": "oklch(94.6% .033 307.174)",
            "200": "oklch(90.2% .063 306.703)",
            "300": "oklch(82.7% .119 306.383)",
            "400": "oklch(71.4% .203 305.504)",
            "500": "oklch(62.7% .265 303.9)",
            "600": "oklch(55.8% .288 302.321)",
            "700": "oklch(49.6% .265 301.924)",
            "800": "oklch(43.8% .218 303.724)",
            "900": "oklch(38.1% .176 304.987)",
            "950": "oklch(29.1% .149 302.717)",
        },  
    },
     
    "SIDEBAR": {
        "show_all_applications": True,
        "show_user": True,                 # Ensure user profile is visible at the bottom
        "navigation": [
            {
                "title": _("Co-Writing"),
                "items": [
                    {
                        "title": _("Stories"),
                        "icon": "auto_stories",
                        "link": reverse_lazy("admin:scene_story_changelist"),
                    },
                    {
                        "title": _("Scene Refine & Extract"),
                        "icon": "movie",
                        "link": reverse_lazy("admin:scene_scene_changelist"),
                    },
                    {
                        "title": _("Scene Organizer"),
                        "icon": "movie",
                        "link": reverse_lazy("admin:scene_sceneorganizer_changelist"),
                    },
                ]
            },
            {
                "title": _("Elements"),
                "separator": True,
                "items": [
                    
                    {
                        "title": _("Props"),
                        "icon": "category",
                        "link": reverse_lazy("admin:scene_prop_changelist"),
                    },
                    {
                        "title": _("Characters"),
                        "icon": "person",
                        "link": reverse_lazy("admin:scene_character_changelist"),
                    },
                    {
                        "title": _("Locations"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:scene_background_changelist"),
                    },
                    {
                        "title": _("Voices"),
                        "icon": "record_voice_over",
                        "link": reverse_lazy("admin:scene_voice_changelist"),
                    },
                ]
            },
            {
                "title": _("Shots"),
                "separator": True,
                "items": [

                    {
                        "title": _("Image Shots"),
                        "icon": "play_arrow",
                        "link": reverse_lazy("admin:scene_action_changelist"),
                    },
                    {
                        "title": _("Comic Shots"),
                        "icon": "auto_awesome",
                        "link": reverse_lazy("admin:scene_comicaction_changelist"),
                    },
                    {
                        "title": _("Video Shots"),
                        "icon": "videocam",
                        "link": reverse_lazy("admin:scene_videoaction_changelist"),
                    },
                    {
                        "title": _("Voice Shots"),
                        "icon": "mic",
                        "link": reverse_lazy("admin:scene_voiceaction_changelist"),
                    },
                    {
                        "title": _("Shot Organizer"),
                        "icon": "play_arrow",
                        "link": reverse_lazy("admin:scene_actionorganizer_changelist"),
                    },
                ],
            },
            {
                "title": _("Personal Area"),
                "separator": True,
                "items": [
                    {
                        "title": _("Groups"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:scene_storygroup_changelist"),
                    },
                    {
                        "title": _("Story Filters"),
                        "icon": "settings",
                        "link": storyprofile,
                    },
                    {
                        "title": _("My Apis"),
                        "icon": "api",
                        "link": agentprofile,
                    },
                    {
                        "title": _("Token Usage"),
                        "icon": "monitoring",
                        "link": token_usage_link,
                    }
                ],
            },
            {
                "title": _("Rendering"),
                "separator": True,
                "items": [
                    {
                        "title": _("Renders"),
                        "icon": "video_library",
                        "link": reverse_lazy("admin:scene_render_changelist"),
                    },
                    {
                        "title": _("Render Items"),
                        "icon": "grid_view",
                        "link": reverse_lazy("admin:scene_renderitem_changelist"),
                    },
                ],
            },
        ],
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_TYPE = os.getenv("DATABASE_TYPE", "sqlite")

if DATABASE_TYPE == "sqlite":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("POSTGRES_DB", "guillermo"),
            'USER': os.getenv("POSTGRES_USER", "postgres"),
            'PASSWORD': os.getenv("POSTGRES_PASSWORD", ""),
            'HOST': os.getenv("POSTGRES_HOST", "localhost"),
            'PORT': os.getenv("POSTGRES_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

LANGUAGES = [
    ('en', _('English')),
    ('es', _('Spanish')),
]

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


GOOGLE_GENAI_VERTEX_API_KEY= os.getenv("GOOGLE_GENAI_VERTEX_API_KEY")
FILER_TABLE_ICON_SIZE = 200

USE_TASK_QUEUE = True

CELERY_BROKER_TYPE = os.getenv("CELERY_BROKER_TYPE", "sqlite")
if CELERY_BROKER_TYPE == "sqlite":
    CELERY_BROKER_URL = "sqla+sqlite:///celerydb.sqlite"
else:
    CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", "7200"))
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "7260"))
CELERY_WORKER_PREFETCH_MULTIPLIER = int(os.getenv("CELERY_WORKER_PREFETCH_MULTIPLIER", "1"))

GENAI_REQUEST_TIMEOUT_MS = int(os.getenv("GENAI_REQUEST_TIMEOUT_MS", "300000"))



# How much character context a COMIC generation carries: "off", "text", or "text+image".
# Off by default on purpose -- switching it on changes the prompt sent to a paid model for every
# comic panel, and an existing book was drawn against the current one. See scene/character_locks.py.
COMIC_CHARACTER_CONTEXT = os.getenv("COMIC_CHARACTER_CONTEXT", "off")

TASK_TYPE_GENERATE_IMAGE = 'generate_image'
TASK_TYPE_REFINE_IMAGE = 'refine_image'
TASK_TYPE_GENERATE_VIDEO = 'generate_video'
TASK_TYPE_GENERATE_OMNI_VIDEO = 'generate_video_multimodal'
TASK_TYPE_GENERATE_VIDEO_FIRST_LAST = 'generate_video_first_last'
TASK_TYPE_GENERATE_COMIC = 'generate_comic'
TASK_TYPE_VIDEO_RENDER = 'video_render'
TASK_TYPE_GENERATE_SCENE = 'generate_scene_video'

TASK_TYPE_GENERATE_VOICE = 'generate_voice'
TASK_TYPE_GENERATE_TEXT = 'generate_text'
TASK_TYPE_GENERATE_SCENE = 'generate_scene'

TASK_TYPE_GENERATE_SCENE_ELEMENTS = 'generate_scene_elements'
TASK_TYPE_GENERATE_SCENE_ACTIONS = 'generate_scene_actions'

TASK_TYPE_GENERATE_SCENE_VOICES = 'generate_scene_voices'
TASK_TYPE_GENERATE_SCENE_COMICS = 'generate_scene_comics'

TASK_TYPE_EXTRACT_SCENE = 'extract_scene'
TASK_TYPE_SYNC_EXPORT = 'sync_export'
TASK_TYPE_SYNC_IMPORT = 'sync_import'




TASK_DELEGATES = {
    # generate
    TASK_TYPE_GENERATE_IMAGE: 'scene.tasks.tasks.TaskGenerateImage',
    TASK_TYPE_REFINE_IMAGE: 'scene.tasks.tasks.TaskRefineImage',
    TASK_TYPE_GENERATE_VIDEO: 'scene.tasks.tasks.TaskGenerateVideo',
    TASK_TYPE_GENERATE_OMNI_VIDEO: 'scene.tasks.tasks.TaskGenerateOmniVideo',
    TASK_TYPE_GENERATE_VIDEO_FIRST_LAST: 'scene.tasks.tasks.TaskGenerateVideoFirstLast',
    TASK_TYPE_GENERATE_COMIC: 'scene.tasks.tasks.TaskGenerateComic',
    TASK_TYPE_GENERATE_VOICE: 'scene.tasks.tasks.TaskGenerateVoice',
    
    TASK_TYPE_GENERATE_TEXT: 'agent.tasks.TaskGenerateText',

    TASK_TYPE_GENERATE_SCENE: 'scene.tasks.tasks.TaskGenerateScene',

    TASK_TYPE_GENERATE_SCENE_ELEMENTS: 'scene.tasks.tasks.TaskGenerateElements',
    TASK_TYPE_GENERATE_SCENE_ACTIONS: 'scene.tasks.tasks.TaskGenerateShots',
    
    TASK_TYPE_GENERATE_SCENE_VOICES: 'scene.tasks.tasks.TaskGenerateVoices',
    TASK_TYPE_GENERATE_SCENE_COMICS: 'scene.tasks.tasks.TaskGenerateComics',

    TASK_TYPE_EXTRACT_SCENE: 'scene.tasks.tasks.TaskExtractScene',
    # sync
    TASK_TYPE_SYNC_EXPORT: 'scene.tasks.sync.TaskSyncExport',
    TASK_TYPE_SYNC_IMPORT: 'scene.tasks.sync.TaskSyncImport',
    # render
    TASK_TYPE_VIDEO_RENDER: 'scene.tasks.render.VideoRender',
    
}
IMPORT_EXPORT_TMP_STORAGE_CLASS = 'import_export.tmp_storages.MediaStorage'
TASK_TYPE_CHOICES = (
    (TASK_TYPE_GENERATE_IMAGE, _("Generate Image")),
    (TASK_TYPE_REFINE_IMAGE, _("Refine Image")),
    (TASK_TYPE_GENERATE_VIDEO, _("Generate Video")),
    (TASK_TYPE_GENERATE_VIDEO_FIRST_LAST, _("Video First Last")),
    (TASK_TYPE_GENERATE_OMNI_VIDEO, _("Video Multimodal")),
    (TASK_TYPE_GENERATE_COMIC, _("Generate Comic")),
    (TASK_TYPE_VIDEO_RENDER, _("Render Video")),
    (TASK_TYPE_GENERATE_VOICE, _("Generate Voice")),
    (TASK_TYPE_GENERATE_TEXT, _("Generate Text")),

    (TASK_TYPE_GENERATE_SCENE, _("Generate Scene")),
    (TASK_TYPE_GENERATE_SCENE_ELEMENTS, _("Generate Elements")),
    (TASK_TYPE_GENERATE_SCENE_ACTIONS, _("Generate Shots")),
    (TASK_TYPE_GENERATE_SCENE_VOICES, _("Generate Voices")),
    (TASK_TYPE_GENERATE_SCENE_COMICS, _("Generate Comics")),
    (TASK_TYPE_EXTRACT_SCENE, _("Extract Scene")),
    (TASK_TYPE_SYNC_EXPORT, _("Sync Export")),
    (TASK_TYPE_SYNC_IMPORT, _("Sync Import")),
    (TASK_TYPE_GENERATE_SCENE, _("Generate Scene Video")),

)

TASK_RETRY_EXCEPTIONS = [
    'RESOURCE_EXHAUSTED',
]

# --- Configuración de archivos estáticos ---
import os
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Agent Structured Output Schema Settings
SCHEMA_MULTI_SCENE = "multiscene"
SCHEMA_SCENE = "scene"
SCHEMA_OUTPUT_WITH_MESSAGE = "outwithmsg"
SCHEMA_CREATE_INSTRUCTIONS = "create_instructions"
SCHEMA_ASSETS = "assets"
SCHEMA_STORY_SCENES = "story_scenes"

AGENT_SCHEMA_CHOICES = [
    (SCHEMA_MULTI_SCENE, _("Multi Scene Storyboard")),
    (SCHEMA_SCENE, _("Single Scene Storyboard")),
    (SCHEMA_OUTPUT_WITH_MESSAGE, _("Output With Message")),
    (SCHEMA_CREATE_INSTRUCTIONS, _("Create Instructions")),
    (SCHEMA_STORY_SCENES, _("Story Scenes")),
    (SCHEMA_ASSETS, _("Assets")),

]

AGENT_SCHEMAS = {
    SCHEMA_MULTI_SCENE: "scene.schemas.MultiSceneSchema",
    SCHEMA_SCENE : "scene.schemas.SceneSchema",    
    SCHEMA_OUTPUT_WITH_MESSAGE: "scene.schemas.OutputWithMessageSchema",
    SCHEMA_CREATE_INSTRUCTIONS: "scene.schemas.CreateInstructionsSchema",
    SCHEMA_STORY_SCENES: "scene.schemas.StoryScenesSchema",
    SCHEMA_ASSETS: "scene.schemas.AssetsSchema"
        
}

PRESET_INFO =  "info"
PRESET_INSTRUCTION =  "instruction"


COMMON_TEXT_AGENT_PRESETS = (
    (PRESET_INFO, _("Last message")),
    (PRESET_INSTRUCTION, _("Instruction")),        
)
ACTION_INFO = f"generate_text-preset-{PRESET_INFO}"
ACTION_INSTRUCTION = f"generate_text-preset-{PRESET_INSTRUCTION}-schema-{SCHEMA_OUTPUT_WITH_MESSAGE}"
ACTION_INSTRUCTION_COMMIT = f"generate_text-preset-{PRESET_INSTRUCTION}-schema-{SCHEMA_CREATE_INSTRUCTIONS}"

COMMON_TEXT_ACTION_CHOICES =(
    (ACTION_INFO, _("Info")),
    (ACTION_INSTRUCTION, _("Instruction")),
    (ACTION_INSTRUCTION_COMMIT, _("Instruction Commit")),
)

SYSTEM_PRESETS = [
    PRESET_INFO,
    PRESET_INSTRUCTION,
] 