# Generated by Django 6.0.3 on 2026-07-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_scheduled_at_task_scheduled_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (0, 'Started'), (4, 'Success'), (3, 'Error'), (2, 'Holding'), (5, 'Scheduled'), (6, 'Retry')], default=1),
        ),
    ]
