# Generated by Django 5.2.17 on 2026-08-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_alter_task_task_type_alter_taskpreset_preset_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.SlugField(
                choices=[
                    ("generate_image", "Generate Image"),
                    ("refine_image", "Refine Image"),
                    ("generate_video", "Generate Video"),
                    ("generate_video_first_last", "Video First Last"),
                    ("generate_video_multimodal", "Video Multimodal"),
                    ("generate_comic", "Generate Comic"),
                    ("video_render", "Render Video"),
                    ("generate_voice", "Generate Voice"),
                    ("generate_text", "Generate Text"),
                    ("generate_scene", "Generate Scene"),
                    ("generate_scene_elements", "Generate Elements"),
                    ("generate_scene_actions", "Generate Shots"),
                    ("generate_scene_voices", "Generate Voices"),
                    ("generate_scene_comics", "Generate Comics"),
                    ("extract_scene", "Extract Scene"),
                    ("sync_export", "Sync Export"),
                    ("sync_import", "Sync Import"),
                    ("letter_action", "Letter Panel"),
                    ("generate_scene", "Generate Scene Video"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="taskpreset",
            name="preset_type",
            field=models.SlugField(
                choices=[
                    ("generate_image", "Generate Image"),
                    ("refine_image", "Refine Image"),
                    ("generate_video", "Generate Video"),
                    ("generate_video_first_last", "Video First Last"),
                    ("generate_video_multimodal", "Video Multimodal"),
                    ("generate_comic", "Generate Comic"),
                    ("video_render", "Render Video"),
                    ("generate_voice", "Generate Voice"),
                    ("generate_text", "Generate Text"),
                    ("generate_scene", "Generate Scene"),
                    ("generate_scene_elements", "Generate Elements"),
                    ("generate_scene_actions", "Generate Shots"),
                    ("generate_scene_voices", "Generate Voices"),
                    ("generate_scene_comics", "Generate Comics"),
                    ("extract_scene", "Extract Scene"),
                    ("sync_export", "Sync Export"),
                    ("sync_import", "Sync Import"),
                    ("letter_action", "Letter Panel"),
                    ("generate_scene", "Generate Scene Video"),
                ]
            ),
        ),
    ]
