# Generated by Django 6.0.3 on 2026-07-16 10:07

import django.db.models.deletion
import filer.fields.file
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_alter_agent_output_type'),
        ('filer', '0018_alter_file_options'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='message',
            name='output_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='output_image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='output_text',
        ),
        migrations.CreateModel(
            name='AgentApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='agent.agent', verbose_name='agent')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='agent.googleapikey', verbose_name='agent')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='agent.agentprofile', verbose_name='profile')),
            ],
        ),
        migrations.CreateModel(
            name='MessagePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], default='input', max_length=10, verbose_name='part type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='json data')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_parts_file', to='filer.file', verbose_name='file')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_parts_image', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='agent.message')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('message', 'order')},
            },
        ),
    ]
