# Generated by Django 6.0.3 on 2026-07-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_remove_message_input_data_remove_message_output_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepart',
            name='part_type',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('instructions', 'Instructions')], default='input', max_length=31, verbose_name='part type'),
        ),
    ]
