# Generated by Django 6.0.3 on 2026-07-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_alter_messagepart_part_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagepart',
            unique_together=set(),
        ),
    ]
