# Generated by Django 6.0.3 on 2026-07-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_alter_messagepart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='messagepart',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='key'),
        ),
    ]
