# Generated by Django 6.0.3 on 2026-07-25 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_historicalprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100, verbose_name='name')),
                ('slug', models.SlugField(default='slug', max_length=100, verbose_name='slug')),
            ],
        ),
        migrations.AddField(
            model_name='historicalprompt',
            name='categories',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agent.promptcategory', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='agent.promptcategory', verbose_name='categories'),
        ),
    ]
