# Generated by Django 6.0.3 on 2026-07-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_promptcategory_historicalprompt_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprompt',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='categories',
        ),
        migrations.AddField(
            model_name='prompt',
            name='categories',
            field=models.ManyToManyField(blank=True, to='agent.promptcategory', verbose_name='categories'),
        ),
    ]
