# Generated by Django 6.0.3 on 2026-08-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_remove_historicalprompt_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='schema',
            field=models.CharField(blank=True, choices=[('multiscene', 'Multi Scene Storyboard'), ('scene', 'Single Scene Storyboard'), ('outwithmsg', 'Output With Message')], max_length=100, null=True, verbose_name='schema'),
        ),
    ]
