# Generated by Django 6.0.3 on 2026-08-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_alter_agent_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='preset',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='preset'),
        ),
    ]
