# Generated by Django 6.0.3 on 2026-08-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0018_message_preset'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompt',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='messagepart',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='messagepart',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='schema',
            field=models.CharField(blank=True, choices=[('multiscene', 'Multi Scene Storyboard'), ('scene', 'Single Scene Storyboard'), ('outwithmsg', 'Output With Message'), ('create_instructions', 'Create Instructions'), ('story_scenes', 'Story Scenes')], max_length=100, null=True, verbose_name='schema'),
        ),
    ]
