# Generated by Django 6.0.3 on 2026-08-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0019_alter_prompt_options_messagepart_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompt',
            options={},
        ),
        migrations.RemoveField(
            model_name='messagepart',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='messagepart',
            name='object_id',
        ),
    ]
