# Generated by Django 6.0.3 on 2026-08-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0020_alter_prompt_options_remove_messagepart_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprompt',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Prompt', 'verbose_name_plural': 'historical Prompts'},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'ordering': ['order'], 'verbose_name': 'Prompt', 'verbose_name_plural': 'Prompts'},
        ),
    ]
