# Generated by Django 6.0.3 on 2026-08-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0021_alter_historicalprompt_options_alter_prompt_options'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepart',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='messagepart',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='schema',
            field=models.CharField(blank=True, choices=[('multiscene', 'Multi Scene Storyboard'), ('scene', 'Single Scene Storyboard'), ('outwithmsg', 'Output With Message'), ('create_instructions', 'Create Instructions'), ('story_scenes', 'Story Scenes'), ('assets', 'Assets')], max_length=100, null=True, verbose_name='schema'),
        ),
    ]
